/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Certificate = IDL.Record({
  'completionDate' : IDL.Text,
  'name' : IDL.Text,
  'courseName' : IDL.Text,
  'certificateCode' : IDL.Text,
});
export const InquiryType = IDL.Variant({
  'support' : IDL.Null,
  'partnership' : IDL.Null,
  'feedback' : IDL.Null,
  'general' : IDL.Null,
});
export const ContactFormSubmission = IDL.Record({
  'inquiryType' : InquiryType,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'message' : IDL.Text,
});

export const idlService = IDL.Service({
  'addCertificate' : IDL.Func([Certificate], [], []),
  'getAllContactFormSubmissions' : IDL.Func(
      [],
      [IDL.Vec(ContactFormSubmission)],
      ['query'],
    ),
  'submitContactForm' : IDL.Func([ContactFormSubmission], [], []),
  'verifyCertificate' : IDL.Func([IDL.Text], [Certificate], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Certificate = IDL.Record({
    'completionDate' : IDL.Text,
    'name' : IDL.Text,
    'courseName' : IDL.Text,
    'certificateCode' : IDL.Text,
  });
  const InquiryType = IDL.Variant({
    'support' : IDL.Null,
    'partnership' : IDL.Null,
    'feedback' : IDL.Null,
    'general' : IDL.Null,
  });
  const ContactFormSubmission = IDL.Record({
    'inquiryType' : InquiryType,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'message' : IDL.Text,
  });
  
  return IDL.Service({
    'addCertificate' : IDL.Func([Certificate], [], []),
    'getAllContactFormSubmissions' : IDL.Func(
        [],
        [IDL.Vec(ContactFormSubmission)],
        ['query'],
      ),
    'submitContactForm' : IDL.Func([ContactFormSubmission], [], []),
    'verifyCertificate' : IDL.Func([IDL.Text], [Certificate], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };