/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface ContactFormSubmission {
    inquiryType: InquiryType;
    name: string;
    submittedAt: string;
    email: string;
    message: string;
}
export interface Certificate {
    completionDate: string;
    name: string;
    courseName: string;
    certificateCode: string;
}
export interface ReviewInput {
    courseOrProject: string;
    name: string;
    role: string;
    submittedAt: string;
    comment: string;
    stars: bigint;
}
export interface Review {
    id: bigint;
    status: ReviewStatus;
    courseOrProject: string;
    name: string;
    role: string;
    submittedAt: string;
    comment: string;
    stars: bigint;
}
export enum InquiryType {
    support = "support",
    partnership = "partnership",
    feedback = "feedback",
    general = "general"
}
export enum ReviewStatus {
    pending = "pending",
    approved = "approved",
    rejected = "rejected"
}
export interface backendInterface {
    addCertificate(certificate: Certificate): Promise<void>;
    approveReview(id: bigint): Promise<void>;
    getAllContactFormSubmissions(): Promise<Array<ContactFormSubmission>>;
    getAllReviews(): Promise<Array<Review>>;
    getApprovedReviews(): Promise<Array<Review>>;
    getPendingReviews(): Promise<Array<Review>>;
    rejectReview(id: bigint): Promise<void>;
    submitContactForm(submission: ContactFormSubmission): Promise<void>;
    submitReview(review: ReviewInput): Promise<bigint>;
    verifyCertificate(code: string): Promise<Certificate>;
}
import type { ContactFormSubmission as _ContactFormSubmission, InquiryType as _InquiryType, Review as _Review, ReviewStatus as _ReviewStatus } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addCertificate(arg0: Certificate): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addCertificate(arg0);
            return result;
        }
    }
    async approveReview(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.approveReview(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.approveReview(arg0);
            return result;
        }
    }
    async getAllContactFormSubmissions(): Promise<Array<ContactFormSubmission>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllContactFormSubmissions();
                return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllContactFormSubmissions();
            return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllReviews(): Promise<Array<Review>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllReviews();
                return from_candid_vec_n6(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllReviews();
            return from_candid_vec_n6(this._uploadFile, this._downloadFile, result);
        }
    }
    async getApprovedReviews(): Promise<Array<Review>> {
        if (this.processError) {
            try {
                const result = await this.actor.getApprovedReviews();
                return from_candid_vec_n6(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getApprovedReviews();
            return from_candid_vec_n6(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPendingReviews(): Promise<Array<Review>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPendingReviews();
                return from_candid_vec_n6(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPendingReviews();
            return from_candid_vec_n6(this._uploadFile, this._downloadFile, result);
        }
    }
    async rejectReview(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.rejectReview(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.rejectReview(arg0);
            return result;
        }
    }
    async submitContactForm(arg0: ContactFormSubmission): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.submitContactForm(to_candid_ContactFormSubmission_n11(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitContactForm(to_candid_ContactFormSubmission_n11(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async submitReview(arg0: ReviewInput): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.submitReview(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitReview(arg0);
            return result;
        }
    }
    async verifyCertificate(arg0: string): Promise<Certificate> {
        if (this.processError) {
            try {
                const result = await this.actor.verifyCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.verifyCertificate(arg0);
            return result;
        }
    }
}
function from_candid_ContactFormSubmission_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ContactFormSubmission): ContactFormSubmission {
    return from_candid_record_n3(_uploadFile, _downloadFile, value);
}
function from_candid_InquiryType_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _InquiryType): InquiryType {
    return from_candid_variant_n5(_uploadFile, _downloadFile, value);
}
function from_candid_ReviewStatus_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ReviewStatus): ReviewStatus {
    return from_candid_variant_n10(_uploadFile, _downloadFile, value);
}
function from_candid_Review_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Review): Review {
    return from_candid_record_n8(_uploadFile, _downloadFile, value);
}
function from_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    inquiryType: _InquiryType;
    name: string;
    submittedAt: string;
    email: string;
    message: string;
}): {
    inquiryType: InquiryType;
    name: string;
    submittedAt: string;
    email: string;
    message: string;
} {
    return {
        inquiryType: from_candid_InquiryType_n4(_uploadFile, _downloadFile, value.inquiryType),
        name: value.name,
        submittedAt: value.submittedAt,
        email: value.email,
        message: value.message
    };
}
function from_candid_record_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: _ReviewStatus;
    courseOrProject: string;
    name: string;
    role: string;
    submittedAt: string;
    comment: string;
    stars: bigint;
}): {
    id: bigint;
    status: ReviewStatus;
    courseOrProject: string;
    name: string;
    role: string;
    submittedAt: string;
    comment: string;
    stars: bigint;
} {
    return {
        id: value.id,
        status: from_candid_ReviewStatus_n9(_uploadFile, _downloadFile, value.status),
        courseOrProject: value.courseOrProject,
        name: value.name,
        role: value.role,
        submittedAt: value.submittedAt,
        comment: value.comment,
        stars: value.stars
    };
}
function from_candid_variant_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    approved: null;
} | {
    rejected: null;
}): ReviewStatus {
    return "pending" in value ? ReviewStatus.pending : "approved" in value ? ReviewStatus.approved : "rejected" in value ? ReviewStatus.rejected : value;
}
function from_candid_variant_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    support: null;
} | {
    partnership: null;
} | {
    feedback: null;
} | {
    general: null;
}): InquiryType {
    return "support" in value ? InquiryType.support : "partnership" in value ? InquiryType.partnership : "feedback" in value ? InquiryType.feedback : "general" in value ? InquiryType.general : value;
}
function from_candid_vec_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ContactFormSubmission>): Array<ContactFormSubmission> {
    return value.map((x)=>from_candid_ContactFormSubmission_n2(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Review>): Array<Review> {
    return value.map((x)=>from_candid_Review_n7(_uploadFile, _downloadFile, x));
}
function to_candid_ContactFormSubmission_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ContactFormSubmission): _ContactFormSubmission {
    return to_candid_record_n12(_uploadFile, _downloadFile, value);
}
function to_candid_InquiryType_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: InquiryType): _InquiryType {
    return to_candid_variant_n14(_uploadFile, _downloadFile, value);
}
function to_candid_record_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    inquiryType: InquiryType;
    name: string;
    submittedAt: string;
    email: string;
    message: string;
}): {
    inquiryType: _InquiryType;
    name: string;
    submittedAt: string;
    email: string;
    message: string;
} {
    return {
        inquiryType: to_candid_InquiryType_n13(_uploadFile, _downloadFile, value.inquiryType),
        name: value.name,
        submittedAt: value.submittedAt,
        email: value.email,
        message: value.message
    };
}
function to_candid_variant_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: InquiryType): {
    support: null;
} | {
    partnership: null;
} | {
    feedback: null;
} | {
    general: null;
} {
    return value == InquiryType.support ? {
        support: null
    } : value == InquiryType.partnership ? {
        partnership: null
    } : value == InquiryType.feedback ? {
        feedback: null
    } : value == InquiryType.general ? {
        general: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
